[build]
  builder = "nixpacks"
  buildCommand = "npx prisma generate --schema=prisma/schema.prisma && next build"

[deploy]
  startCommand = "next start"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 5
